# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aedbbf1c9b2b513a9c4a992bfe97118d408090a252b5edf4d6f637cdf6678ec1aba6c4b2990a115cb235638e2105adba1dd4a91317d093c589399e0116d03cc4

test:
  secret_key_base: ae476adbfc2e72c876bb402818119bc23c865c899a621f9d0b7c1dda339e95833a79ffba764ccb6aa3c6b8943013d9306024e140bbcc2d397399d1d5da2d1a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
